import Head from "next/head";
import Navbar from "../components/Navbar";
import HomeSection from "../components/HomeSection";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import { useTheme } from "next-themes";
import Apps from "../components/Apps";
import Footer from "../components/Footer";

export default function Home() {
  // const appContext = useContext(AppContext);

  return (
    <div>
      <Head>
        <title>Ashwin Gur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div>
        <HomeSection />
        <Projects />
        <Apps />
        <Contact />
      </div>
      <Footer></Footer>
    </div>
  );
}
